
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: share_development

 
test:
  <<: *default
  database: share_test

production:
  <<: *default
  database: share_production
  username: share
  password: <%= ENV['SHARE_DATABASE_PASSWORD'] %>
